apiVersion: v1
kind: Service
metadata:
  name: backend-mysql
  labels:
    name: backend-mysql
    app: my-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mydb-pod
    app: my-app