apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: my-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    
  selector:
    name: web-app-pod
    app: my-app