apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-php-app
  template:
    metadata:
      labels:
        app: web-php-app
    spec:
      containers:
      - name: php-app
        image: frontend:1.3
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80
