apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-php-app
  template:
    metadata:
      labels:
        app: web-php-app
    spec:
      containers:
      - name: php-app
        image: veerabhadraswami/frontend:latest
        ports:
        - containerPort: 80
